#!/bin/sh
##################################################
# ddns client
# Author: leitz@sin360.net 2007.04.25
##################################################
DIRINCLUDE="/mnt/tmp/ddns"

. ${DIRINCLUDE}/ddnsrc

${KILLALLCMD} ${DDNSSTARTCMD}
echo "DDNS stoped"

exit 0