#!/bin/sh
##################################################
# ddns client
# Author: leitz@sin360.net 2007.04.25
##################################################
DIRINCLUDE="/mnt/tmp/ddns"

. ${DIRINCLUDE}/ddnsrc

hostname=""
username=""
userpasswd=""
ispname=""
dnsserver=""
isproxy="no"

if [ "$#" -lt "5" ]; then
	echo "Usage: ddns-config hostname username userpasswd ispname isproxy [dnsserver]"
	echo "Usage: ddns-config stop"
	if [ "$#" -eq "1" ] && [ "$1" == "stop" ]; then
		[ -f ${CONFIGFILE} ] && ${RMCMD} ${CONFIGFILE}
	fi
	exit 1
fi

hostname="$1"            
username="$2"           
userpasswd="$3"
ispname="$4"
isproxy="$5"
dnsserver="$6"
base64="$7"

echo "DOMAINNAME=${hostname}" > ${CONFIGFILE}
echo "USERNAME=${username}" >>  ${CONFIGFILE}
echo "USERPASSWORD=${userpasswd}" >> ${CONFIGFILE}
echo "ISPNAME=${ispname}" >> ${CONFIGFILE}
echo "DNSSERVER=${dnsserver}" >> ${CONFIGFILE}
echo "ISPROXY=${isproxy}" >> ${CONFIGFILE}
echo "BASE64=${base64}" >> ${CONFIGFILE}

echo "${RUNDDNSCMD}.${ispname}" 

if ! [ "${ispname}" == "" ] && [ -f ${RUNDDNSCMD}.${ispname} ]
then
	[ -f ${RUNDDNSCMD} ] && ${RMCMD} ${RUNDDNSCMD}
	[ -f ${RUNDDNSCMD}.${ispname} ] && ${LINKCMD} ${RUNDDNSCMD}.${ispname} ${RUNDDNSCMD} && chmod +x ${RUNDDNSCMD}	
fi

[ -f ${PIDFILE} ] && ${RMCMD} ${PIDFILE}
[ -f ${LOGFILE} ] && ${RMCMD} ${LOGFILE}

echo "ddns config ok" 

exit 0
