#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=60

start() {
	if [ "$($CONFIG get ap_mode)" = "1" ]; then
		# should not start dnsmasq in AP mode
		exit
	fi

	if [ "$($CONFIG get wds_endis_fun)" = "1" -a "$($CONFIG get wds_repeater_basic)" = "0" -o "$($CONFIG get wla_wds_endis_fun)" = "1" -a "$($CONFIG get wds_repeater_basic_a)" = "0" ]; then
		# should not start dnsmasq in WDS repeater mode
		exit
	fi

	[ ! -f /tmp/resolv.conf ] && touch /tmp/resolv.conf

	local opt_argv=""
	local resolv_file="/tmp/resolv.conf"

	# start parental ctl config
	if [ "$($CONFIG get ParentalControl)" = "1" ]; then
		$CONFIG get ParentalControl_table > /tmp/parentalcontrol.conf
		opt_argv="$opt_argv --parental-control"
		resolv_file="/tmp/resolv_opendns.conf"
		echo "nameserver 208.67.222.222" > $resolv_file
		echo "nameserver 208.67.220.220" >> $resolv_file
	fi
	# end parental ctl config

	# start wan ifname config
	if [ "$($CONFIG get wan_proto)" = "pppoe" -o "$($CONFIG get wan_proto)" = "pptp" -o "$($CONFIG get wan_proto)" = "l2tp" ]; then
		opt_argv="$opt_argv --wan-interface=ppp0"
	else
		opt_argv="$opt_argv --wan-interface=$WAN_IF"
	fi
	# end wan ifname config

	/usr/sbin/dnsmasq -r $resolv_file $opt_argv

	if [ "$($CONFIG get dns_hijack)" = "1" ]; then
		sleep 2
		# TRY TO MAKE SURE the `dnsmasq` got the siginal
		killall -SIGUSR1 dnsmasq
		sleep 1
		killall -SIGUSR1 dnsmasq
	fi
}

stop() {
	killall dnsmasq
}
