#!/bin/sh /etc/rc.common
START=19

setup_wan_mac() {
    local mac

    mac="wan_factory_mac"
    if [ "$1" = "dhcp" -o "$1" = "static" ]; then
        value=$($CONFIG get wan_ether_mac_assign)

        if [ "$value" = "1" ]; then
            mac="wan_remote_mac"
        elif [ "$value" = "2" ]; then
            mac="wan_ether_this_mac"
        fi
    elif [ "$1" = "pptp" ]; then
        value=$($CONFIG get wan_pptp_mac_assign)

        if [ "$value" = "1" ]; then
            mac="wan_remote_mac"
        elif [ "$value" = "2" ]; then
            mac="wan_pptp_this_mac"
        fi
    elif [ "$1" = "bigpond" ]; then
        value=$($CONFIG get wan_bpa_mac_assign)

        if [ "$value" = "1" ]; then
            mac="wan_remote_mac"
        elif [ "$value" = "2" ]; then
            mac="wan_bpa_this_mac"
        fi
    elif [ "$1" = "pppoe" ]; then
        value=$($CONFIG get wan_pppoe_mac_assign)

        if [ "$value" = "1" ]; then
            mac="wan_remote_mac"
        elif [ "$value" = "2" ]; then
            mac="wan_pppoe_this_mac"
        fi
    fi

    mac_value=$($CONFIG get $mac)

    ifconfig $WAN_IF down
    ifconfig $WAN_IF hw ether $mac_value
    ifconfig $WAN_IF up
    # Enable DAD, and disable IPv6 operation if MAC-based duplicate link-local address has been found.
    echo 2 > /proc/sys/net/ipv6/conf/eth0/accept_dad
    #make eth0 send NS package
    echo "0" > /proc/sys/net/ipv6/neigh/eth0/not_send_neighbor_solicitation

    sleep 2
    # For IPv6 Ready Log test, fixed ip setting do not enable radvd and dhcpv6s
    local wan6_type=`$CONFIG get ipv6_type`
    local logo_test=`$CONFIG get endis_ipv6_logo_test`
    if [ "x$logo_test" = "x1" -a "x$wan6_type" = "xfixed" ]; then
	/etc/net6conf/6fixed wan
    fi
}

start() {
	if ! grep -q -e ag7240_mod /proc/modules; then
		load_modules /etc/modules.d/50-ag7240-enet
	fi
	# start GPIO reset button & GPIO LED
	if ! grep -q -e ar7240gpio /proc/modules; then
	        load_modules /etc/modules.d/40-ar7240-gpio
	fi
        mknod /dev/ar7240gpio c 240 0
        mknod /dev/ar7240gpiointr c 250 0

	wan_default_mac=$(/sbin/get-default-wan-mac-from-flash)
	wan_default_mac=$(echo -n $wan_default_mac)
	$CONFIG set wan_factory_mac="$wan_default_mac"
	echo "INIT-SWITCH: Default WAN MAC is : $wan_default_mac"

	proto=$($CONFIG get wan_proto)
	setup_wan_mac $proto
}

stop() {
	ifdown $WAN_IF	
	ifdown $LAN_IF	
}

restart() {
	stop
	start
}
