#!/bin/sh /etc/rc.common
START=20

print_dhcpd_conf(){
    cat <<EOF
pidfile /var/run/udhcpd.pid
start $2
end $3
interface $1
remaining yes
auto_time 5
lease_file /tmp/udhcpd.leases
option subnet $4
option router $5
option dns $5
option lease $6
EOF
}
 
start_dhcpd() {
    [ ! -f /tmp/udhcpd.leases ] && touch /tmp/udhcpd.leases
    print_dhcpd_conf "$BR_IF" "$($CONFIG get dhcp_start)" "$($CONFIG get dhcp_end)" "$($CONFIG get lan_netmask)" "$($CONFIG get lan_ipaddr)" "$($CONFIG get lan_lease)" > /tmp/udhcpd.conf

    count=1
    while :
    do
	lease="$($CONFIG get reservation$count)"
	if [ "x$lease" = "x" ]; then
	    break;
	fi
	count=`expr $count + 1`
	echo "static_lease $lease" >> /tmp/udhcpd.conf
    done

    udhcpd /tmp/udhcpd.conf
}

start() {
	local lan_ip lan_mask

	brctl addif $BR_IF $LAN_IF
	lan_default_mac=$(ifconfig $LAN_IF | grep $LAN_IF | sed 's/.*HWaddr//')
	lan_default_mac=$(echo -n $lan_default_mac)
	ifconfig $BR_IF hw ether $lan_default_mac
	#echo "NET-LAN: Default LAN MAC is : $lan_default_mac"

	lan_ip=$($CONFIG get lan_ipaddr)
	lan_mask=$($CONFIG get lan_netmask)

	#ifconfig $BR_IF ${lan_ip:-192.168.1.1} netmask ${lan_mask:-255.255.255.0}
	
	ifconfig $LAN_IF up
	sleep 10
	ifconfig $BR_IF ${lan_ip:-192.168.1.1} netmask ${lan_mask:-255.255.255.0}
	ifconfig $BR_IF up
	ifconfig $BR_IF down
	#Enable DAD, and disable IPv6 operation if MAC-based duplicate link-local address has been found.
	echo 2 > /proc/sys/net/ipv6/conf/br0/accept_dad
	#make the interface "br0" send NS package, "eth1" don't send
	echo "1" > /proc/sys/net/ipv6/neigh/eth1/not_send_neighbor_solicitation
	echo "0" > /proc/sys/net/ipv6/neigh/br0/not_send_neighbor_solicitation
	ifconfig $BR_IF up
	echo "1" > /proc/sys/net/ipv6/neigh/eth1/not_send_neighbor_solicitation
	echo "0" > /proc/sys/net/ipv6/neigh/br0/not_send_neighbor_solicitation

	sleep 2
        # For IPv6 Ready Log test, fixed ip setting do not enable radvd and dhcpv6s
        local wan6_type=`$CONFIG get ipv6_type`
        local logo_test=`$CONFIG get endis_ipv6_logo_test`
        if [ "x$logo_test" = "x1" -a "x$wan6_type" = "xfixed" ]; then
		/etc/net6conf/6fixed lan
	fi

	[ "$($CONFIG get lan_dhcp)" = "1" ] && start_dhcpd

	# Attach Device
	mkdir -p /tmp/netscan
	/usr/sbin/net-scan

	# Restart UPnP
	[ ! -f /tmp/boot_status ] && /sbin/cmdupnp restart

	# Start Router Debugging Mode ...
	. /lib/network/RtDebug.sh
	start_RtDebugMode

        # Apply static route    
        /sbin/cmdroute start

	# HNAP
	/usr/sbin/hnapd
}

stop() {
	killall udhcpd
	killall net-scan
	killall hnapd
	ifdown $LAN_IF	

	# PHY link will be pulled low some seconds to force transition to reboot state 
	# and generating DHCP request and Discovery protocol and address refresh in the 
	# devices connected to the NETGEAR Local Area Network ports.
	[ "x$($CONFIG get hnap_test)" != "x1" ] && echo -n 9 > /proc/switch_phy
	$CONFIG set hnap_test=0
}

restart() {
	stop
	start
}
