#!/bin/sh 
# Copyright (C) 2006 OpenWrt.org

/etc/preinit.arch

echo 1 > /tmp/boot_status
for i in /etc/rc.d/S*; do
	$i boot
done 
rm -rf /tmp/boot_status

echo 1 > /proc/sys/kernel/panic

echo 4096 > /proc/sys/vm/min_free_kbytes
echo 5 > /proc/sys/vm/dirty_ratio
echo 5 > /proc/sys/vm/dirty_background_ratio
echo 4096 > /proc/sys/net/ipv4/ip_conntrack_max
echo 32 > /proc/sys/net/ipv4/ip_conntrack_icmp_reserve_max
echo 480 > /proc/sys/net/ipv4/ip_conntrack_tcp_reserve_max
echo 4096 > /proc/sys/net/ipv4/ip_conntrack_local_max
echo 32 > /proc/sys/net/ipv4/ip_conntrack_local_icmp_reserve_max
echo 480 > /proc/sys/net/ipv4/ip_conntrack_local_tcp_reserve_max
echo 1024 > /proc/sys/net/ipv4/bridge_max_fdb_entry
echo 60 > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_syn_sent
#echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
#echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter
#if [ -d /proc/sys/net/ipv4/conf/eth0 ] ; then
#        echo 1 > /proc/sys/net/ipv4/conf/eth0/rp_filter
#fi
#if [ -d /proc/sys/net/ipv4/conf/ppp0 ] ; then
#        echo 1 > /proc/sys/net/ipv4/conf/ppp0/rp_filter
#fi
echo 1 > /proc/sys/net/ipv4/ipfrag_overlap_drop
echo 1 > /proc/sys/net/ipv4/route/send_first_redirect_anyway
echo 1 > /proc/sys/net/ipv4/ipfrag_protect_jolt2
